const productsTypes = {
  ADICIONAR_NOVO_PRODUTO_COMECO: 'ADICIONAR_NOVO_PRODUTO_COMECO',
  FETCH_BUSCAR_PRODUTOS_COMECO: 'FETCH_BUSCAR_PRODUTOS_COMECO',
  SET_PRODUTOS: 'SET_PRODUTOS',
  DELETAR_PRODUTOS: 'DELETAR_PRODUTOS',
  
};

export default productsTypes